### ISSUE TITLE
run docker image

### ISSUE THREAD

**Issue by wicksome** [wicksome/sonar-l10n-ko#3]
```
$ docker run -p 9000:9000 -it --rm sonarqube:8.7-developer
```

**Comment by wicksome** [comment]
```
version: "3.7"
services:
  sonarqube:
    image: sonarqube:8.7-developer
    depends_on:
      - postgresql
    container_name: sonarqube
    networks:
      - sonarnet
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgresql:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - type: volume
        source: sonar_extensions
        target: /opt/sonarqube/extensions
  postgresql:
    image: postgres:10.11
    container_name: postgres
    restart: always
    networks:
      - sonarnet
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - type: volume
        source: postgresql
        target: /var/lib/postgresql/data
volumes:
  sonar_extensions:
  postgresql:
networks:
  sonarnet:
    driver: bridge
```

```
dkc up -t 3600
dk volume ls
dk volume inspect sonar-l10n-ko_sonar_extensions 
```
